stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - data_given/file1.csv
    outs:
    - data/raw/file1.csv

  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
    - src/split_data.py
    - data/raw/file1.csv
    outs:
    - data/processed/train_file1.csv
    - data/processed/test_file1.csv 

  train_and_evaluate:
    cmd: python src/train_and_evaluate.py --config=params.yaml
    deps:
    - data/processed/train_file1.csv
    - data/processed/test_file1.csv 
    - src/train_and_evaluate.py
    params:
    - estimators.RandomForestClassifier.params.n_estimators
    metrics:
    - report/scores.json:
        cache: false
    - report/params.json:
        cache: false
    outs:
    - saved_models/model.joblib